### ISSUE TITLE
ValueError: must produce aggregated value

### ISSUE THREAD

**Issue by ekernf01** [snap-stanford/GEARS#20]
Hi Yusuf et al., I ran into this error while preparing the data split, and I cannot figure out how to proceed. Is there a way to fix the input data? Thank you for your help and let me know if you need other info -- here are the details. 

OS: Ubuntu 20.04
Python: 3.9.15
GEARS: 0.0.4
Traceback:
```
pert_data.prepare_split(split = 'simulation' )
Creating new splits....
Traceback (most recent call last):
  File "/home/ubuntu/mambaforge/envs/ggrn/lib/python3.9/site-packages/pandas/core/groupby/generic.py", line 260, in aggregate
    return self._python_agg_general(
  File "/home/ubuntu/mambaforge/envs/ggrn/lib/python3.9/site-packages/pandas/core/groupby/groupby.py", line 1085, in _python_agg_general
    result, counts = self.grouper.agg_series(obj, f)
  File "/home/ubuntu/mambaforge/envs/ggrn/lib/python3.9/site-packages/pandas/core/groupby/ops.py", line 644, in agg_series
    return self._aggregate_series_pure_python(obj, func)
  File "/home/ubuntu/mambaforge/envs/ggrn/lib/python3.9/site-packages/pandas/core/groupby/ops.py", line 717, in _aggregate_series_pure_python
    raise ValueError("Function does not reduce")
ValueError: Function does not reduce

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/mambaforge/envs/ggrn/lib/python3.9/site-packages/gears/pertdata.py", line 264, in prepare_split
    set2conditions = dict(adata.obs.groupby('split').agg({'condition':
  File "/home/ubuntu/mambaforge/envs/ggrn/lib/python3.9/site-packages/pandas/core/groupby/generic.py", line 951, in aggregate
    result, how = self._aggregate(func, *args, **kwargs)
  File "/home/ubuntu/mambaforge/envs/ggrn/lib/python3.9/site-packages/pandas/core/base.py", line 416, in _aggregate
    result = _agg(arg, _agg_1dim)
  File "/home/ubuntu/mambaforge/envs/ggrn/lib/python3.9/site-packages/pandas/core/base.py", line 383, in _agg
    result[fname] = func(fname, agg_how)
  File "/home/ubuntu/mambaforge/envs/ggrn/lib/python3.9/site-packages/pandas/core/base.py", line 367, in _agg_1dim
    return colg.aggregate(how)
  File "/home/ubuntu/mambaforge/envs/ggrn/lib/python3.9/site-packages/pandas/core/groupby/generic.py", line 267, in aggregate
    result = self._aggregate_named(func, *args, **kwargs)
  File "/home/ubuntu/mambaforge/envs/ggrn/lib/python3.9/site-packages/pandas/core/groupby/generic.py", line 482, in _aggregate_named
    raise ValueError("Must produce aggregated value")
ValueError: Must produce aggregated value
```

To reproduce:

```bash
wget https://www.dropbox.com/s/yvyty40vvr7j7h8/test.h5ad
```

```python
import scanpy as sc
import numpy as np
import scipy
import shutil
from gears import PertData as GEARSPertData
from gears import GEARS
train = sc.read_h5ad("test.h5ad")
def reformat_perturbation_for_gears(perturbation):
    perturbation = perturbation.split(",")
    perturbation = ["ctrl"] + [p if p in train.var.index else "ctrl" for p in perturbation]
    perturbation = list(set(perturbation)) # avoid ctrl+ctrl
    perturbation = "+".join(perturbation)
    return perturbation


train.var['gene_name'] = train.var.index
train.obs['condition'] = [reformat_perturbation_for_gears(p) for p in train.obs['perturbation']]
train.obs['cell_type'] = "all"
for k in train.obs.columns:
    train.obs[k] = train.obs[k].astype("str") 


train.uns["log1p"] = dict()
train.uns["log1p"]["base"] = np.exp(1)
train.uns["perturbed_and_measured_genes"] = list(train.uns["perturbed_and_measured_genes"])
train.uns["perturbed_but_not_measured_genes"] = list(train.uns["perturbed_but_not_measured_genes"])
train.X = scipy.sparse.csr_matrix(train.X)
# Clean up any previous runs
try:
    shutil.rmtree("./gears_input")
except FileNotFoundError:
    pass


pert_data = GEARSPertData("./gears_input", default_pert_graph = True)
pert_data.new_data_process(dataset_name = 'current', adata = train)
pert_data.load(data_path = './gears_input/current')
pert_data.prepare_split(split = 'simulation', seed = 1 )
```

**Comment by yhr91** [comment]
Thanks for your question. Hmm... I was able to run the exact same code without any errors. It seems like there's an error in pandas, which version of pandas are you using
