### ISSUE TITLE
tutorial_inference_Norman.ipynb is out-of-date

### ISSUE THREAD

**Issue by jzqin** [snap-stanford/GEARS#44]
When trying to run the `tutorial_inference_Norman.ipynb` file, loading the pretrained model generates the following error: 

```
TypeError                                 Traceback (most recent call last)
Cell In[111], line 6
      1 gears_model = GEARS(pert_data, 
      2                     device = 'cpu',
      3                     weight_bias_track = False,
      4                     proj_name = 'gears',
      5                     exp_name = 'test')
----> 6 gears_model.load_pretrained('../model/model_ckpt')

File ~/miniconda3/envs/gears/lib/python3.10/site-packages/gears/gears.py:257, in GEARS.load_pretrained(self, path)
    254     config = pickle.load(f)
    256 del config['device'], config['num_genes'], config['num_perts']
--> 257 self.model_initialize(**config)
    258 self.config = config
    260 state_dict = torch.load(os.path.join(path, 'model.pt'), map_location = torch.device('cpu'))

TypeError: GEARS.model_initialize() got an unexpected keyword argument 'cell_fitness_pred'
```

This is because the `model.py` file was updated with the commit `8da5e36`, which removed the `cell_fitness_pred` argument, but the model checkpoint provided via 
`dataverse_download('https://dataverse.harvard.edu/api/access/datafile/6979956', './model.zip')` does not use the updated model.

**Comment by yhr91** [comment]
Sorry for the dealyed response! I've updated the tutorial files and this should now work out of the box.

**Comment by KyleFerchen** [comment]
I am still getting this error as of 2024/10/07:

```BASH
>>> gears_model.load_pretrained('./model_ckpt')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/users/fero3l/env/gears/lib/python3.10/site-packages/gears/gears.py", line 257, in load_pretrained
    self.model_initialize(**config)
TypeError: GEARS.model_initialize() got an unexpected keyword argument 'cell_fitness_pred'
```

**Comment by ManuelMoradiellos** [comment]
Hi! I want to join in this conversation as well, because I was trying to replicate [Fig. 4](https://github.com/yhr91/GEARS_misc/blob/main/paper/Fig4_UMAP_predict.py) and [Fig. 5b](https://github.com/yhr91/GEARS_misc/blob/main/paper/Fig5b.ipynb) from the paper as I wanted to create the predictions' metrics heatmap for my own data, and I got the exact same error when loading the Norman pretrained model. 

I will try with another dataset but maybe it's something related to the Norman one.
Thanks in advance for the package and help provided~

**Comment by jzqin** [comment]
@ManuelMoradiellos the `GEARS_misc` package uses a different (older) version of GEARS compared to the main repo. I suggest cloning the `GEARS_misc` repo and using it by adding the directory to your local path, through something like 

```
sys.path.append('/path/to/GEARS_misc/')
from gears import PertData, GEARS
